/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetCharactersCharacterIdMailRecipient,
    GetCharactersCharacterIdMailRecipientFromJSON,
    GetCharactersCharacterIdMailRecipientFromJSONTyped,
    GetCharactersCharacterIdMailRecipientToJSON,
} from './';

/**
 * 200 ok object
 * @export
 * @interface GetCharactersCharacterIdMail200Ok
 */
export interface GetCharactersCharacterIdMail200Ok {
    /**
     * From whom the mail was sent
     * @type {number}
     * @memberof GetCharactersCharacterIdMail200Ok
     */
    from?: number;
    /**
     * is_read boolean
     * @type {boolean}
     * @memberof GetCharactersCharacterIdMail200Ok
     */
    isRead?: boolean;
    /**
     * labels array
     * @type {Array<number>}
     * @memberof GetCharactersCharacterIdMail200Ok
     */
    labels?: Array<number>;
    /**
     * mail_id integer
     * @type {number}
     * @memberof GetCharactersCharacterIdMail200Ok
     */
    mailId?: number;
    /**
     * Recipients of the mail
     * @type {Array<GetCharactersCharacterIdMailRecipient>}
     * @memberof GetCharactersCharacterIdMail200Ok
     */
    recipients?: Array<GetCharactersCharacterIdMailRecipient>;
    /**
     * Mail subject
     * @type {string}
     * @memberof GetCharactersCharacterIdMail200Ok
     */
    subject?: string;
    /**
     * When the mail was sent
     * @type {Date}
     * @memberof GetCharactersCharacterIdMail200Ok
     */
    timestamp?: Date;
}

export function GetCharactersCharacterIdMail200OkFromJSON(json: any): GetCharactersCharacterIdMail200Ok {
    return GetCharactersCharacterIdMail200OkFromJSONTyped(json, false);
}

export function GetCharactersCharacterIdMail200OkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCharactersCharacterIdMail200Ok {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': !exists(json, 'from') ? undefined : json['from'],
        'isRead': !exists(json, 'is_read') ? undefined : json['is_read'],
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
        'mailId': !exists(json, 'mail_id') ? undefined : json['mail_id'],
        'recipients': !exists(json, 'recipients') ? undefined : ((json['recipients'] as Array<any>).map(GetCharactersCharacterIdMailRecipientFromJSON)),
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'timestamp': !exists(json, 'timestamp') ? undefined : (new Date(json['timestamp'])),
    };
}

export function GetCharactersCharacterIdMail200OkToJSON(value?: GetCharactersCharacterIdMail200Ok | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': value.from,
        'is_read': value.isRead,
        'labels': value.labels,
        'mail_id': value.mailId,
        'recipients': value.recipients === undefined ? undefined : ((value.recipients as Array<any>).map(GetCharactersCharacterIdMailRecipientToJSON)),
        'subject': value.subject,
        'timestamp': value.timestamp === undefined ? undefined : (value.timestamp.toISOString()),
    };
}


