/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetCharactersCharacterIdMailMailIdRecipient,
    GetCharactersCharacterIdMailMailIdRecipientFromJSON,
    GetCharactersCharacterIdMailMailIdRecipientFromJSONTyped,
    GetCharactersCharacterIdMailMailIdRecipientToJSON,
} from './';

/**
 * 200 ok object
 * @export
 * @interface GetCharactersCharacterIdMailMailIdOk
 */
export interface GetCharactersCharacterIdMailMailIdOk {
    /**
     * Mail's body
     * @type {string}
     * @memberof GetCharactersCharacterIdMailMailIdOk
     */
    body?: string;
    /**
     * From whom the mail was sent
     * @type {number}
     * @memberof GetCharactersCharacterIdMailMailIdOk
     */
    from?: number;
    /**
     * Labels attached to the mail
     * @type {Array<number>}
     * @memberof GetCharactersCharacterIdMailMailIdOk
     */
    labels?: Array<number>;
    /**
     * Whether the mail is flagged as read
     * @type {boolean}
     * @memberof GetCharactersCharacterIdMailMailIdOk
     */
    read?: boolean;
    /**
     * Recipients of the mail
     * @type {Array<GetCharactersCharacterIdMailMailIdRecipient>}
     * @memberof GetCharactersCharacterIdMailMailIdOk
     */
    recipients?: Array<GetCharactersCharacterIdMailMailIdRecipient>;
    /**
     * Mail subject
     * @type {string}
     * @memberof GetCharactersCharacterIdMailMailIdOk
     */
    subject?: string;
    /**
     * When the mail was sent
     * @type {Date}
     * @memberof GetCharactersCharacterIdMailMailIdOk
     */
    timestamp?: Date;
}

export function GetCharactersCharacterIdMailMailIdOkFromJSON(json: any): GetCharactersCharacterIdMailMailIdOk {
    return GetCharactersCharacterIdMailMailIdOkFromJSONTyped(json, false);
}

export function GetCharactersCharacterIdMailMailIdOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCharactersCharacterIdMailMailIdOk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': !exists(json, 'body') ? undefined : json['body'],
        'from': !exists(json, 'from') ? undefined : json['from'],
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
        'read': !exists(json, 'read') ? undefined : json['read'],
        'recipients': !exists(json, 'recipients') ? undefined : ((json['recipients'] as Array<any>).map(GetCharactersCharacterIdMailMailIdRecipientFromJSON)),
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'timestamp': !exists(json, 'timestamp') ? undefined : (new Date(json['timestamp'])),
    };
}

export function GetCharactersCharacterIdMailMailIdOkToJSON(value?: GetCharactersCharacterIdMailMailIdOk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': value.body,
        'from': value.from,
        'labels': value.labels,
        'read': value.read,
        'recipients': value.recipients === undefined ? undefined : ((value.recipients as Array<any>).map(GetCharactersCharacterIdMailMailIdRecipientToJSON)),
        'subject': value.subject,
        'timestamp': value.timestamp === undefined ? undefined : (value.timestamp.toISOString()),
    };
}


