/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * factory_details object
 * @export
 * @interface GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails
 */
export interface GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails {
    /**
     * schematic_id integer
     * @type {number}
     * @memberof GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails
     */
    schematicId: number;
}

export function GetCharactersCharacterIdPlanetsPlanetIdFactoryDetailsFromJSON(json: any): GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails {
    return GetCharactersCharacterIdPlanetsPlanetIdFactoryDetailsFromJSONTyped(json, false);
}

export function GetCharactersCharacterIdPlanetsPlanetIdFactoryDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schematicId': json['schematic_id'],
    };
}

export function GetCharactersCharacterIdPlanetsPlanetIdFactoryDetailsToJSON(value?: GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schematic_id': value.schematicId,
    };
}


