/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * dogma_effect object
 * @export
 * @interface GetDogmaDynamicItemsTypeIdItemIdDogmaEffect
 */
export interface GetDogmaDynamicItemsTypeIdItemIdDogmaEffect {
    /**
     * effect_id integer
     * @type {number}
     * @memberof GetDogmaDynamicItemsTypeIdItemIdDogmaEffect
     */
    effectId: number;
    /**
     * is_default boolean
     * @type {boolean}
     * @memberof GetDogmaDynamicItemsTypeIdItemIdDogmaEffect
     */
    isDefault: boolean;
}

export function GetDogmaDynamicItemsTypeIdItemIdDogmaEffectFromJSON(json: any): GetDogmaDynamicItemsTypeIdItemIdDogmaEffect {
    return GetDogmaDynamicItemsTypeIdItemIdDogmaEffectFromJSONTyped(json, false);
}

export function GetDogmaDynamicItemsTypeIdItemIdDogmaEffectFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDogmaDynamicItemsTypeIdItemIdDogmaEffect {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'effectId': json['effect_id'],
        'isDefault': json['is_default'],
    };
}

export function GetDogmaDynamicItemsTypeIdItemIdDogmaEffectToJSON(value?: GetDogmaDynamicItemsTypeIdItemIdDogmaEffect | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'effect_id': value.effectId,
        'is_default': value.isDefault,
    };
}


