/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetFwLeaderboardsKills,
    GetFwLeaderboardsKillsFromJSON,
    GetFwLeaderboardsKillsFromJSONTyped,
    GetFwLeaderboardsKillsToJSON,
    GetFwLeaderboardsVictoryPoints,
    GetFwLeaderboardsVictoryPointsFromJSON,
    GetFwLeaderboardsVictoryPointsFromJSONTyped,
    GetFwLeaderboardsVictoryPointsToJSON,
} from './';

/**
 * 200 ok object
 * @export
 * @interface GetFwLeaderboardsOk
 */
export interface GetFwLeaderboardsOk {
    /**
     * 
     * @type {GetFwLeaderboardsKills}
     * @memberof GetFwLeaderboardsOk
     */
    kills: GetFwLeaderboardsKills;
    /**
     * 
     * @type {GetFwLeaderboardsVictoryPoints}
     * @memberof GetFwLeaderboardsOk
     */
    victoryPoints: GetFwLeaderboardsVictoryPoints;
}

export function GetFwLeaderboardsOkFromJSON(json: any): GetFwLeaderboardsOk {
    return GetFwLeaderboardsOkFromJSONTyped(json, false);
}

export function GetFwLeaderboardsOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFwLeaderboardsOk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kills': GetFwLeaderboardsKillsFromJSON(json['kills']),
        'victoryPoints': GetFwLeaderboardsVictoryPointsFromJSON(json['victory_points']),
    };
}

export function GetFwLeaderboardsOkToJSON(value?: GetFwLeaderboardsOk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kills': GetFwLeaderboardsKillsToJSON(value.kills),
        'victory_points': GetFwLeaderboardsVictoryPointsToJSON(value.victoryPoints),
    };
}


