/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetFwStatsKills,
    GetFwStatsKillsFromJSON,
    GetFwStatsKillsFromJSONTyped,
    GetFwStatsKillsToJSON,
    GetFwStatsVictoryPoints,
    GetFwStatsVictoryPointsFromJSON,
    GetFwStatsVictoryPointsFromJSONTyped,
    GetFwStatsVictoryPointsToJSON,
} from './';

/**
 * 200 ok object
 * @export
 * @interface GetFwStats200Ok
 */
export interface GetFwStats200Ok {
    /**
     * faction_id integer
     * @type {number}
     * @memberof GetFwStats200Ok
     */
    factionId: number;
    /**
     * 
     * @type {GetFwStatsKills}
     * @memberof GetFwStats200Ok
     */
    kills: GetFwStatsKills;
    /**
     * How many pilots fight for the given faction
     * @type {number}
     * @memberof GetFwStats200Ok
     */
    pilots: number;
    /**
     * The number of solar systems controlled by the given faction
     * @type {number}
     * @memberof GetFwStats200Ok
     */
    systemsControlled: number;
    /**
     * 
     * @type {GetFwStatsVictoryPoints}
     * @memberof GetFwStats200Ok
     */
    victoryPoints: GetFwStatsVictoryPoints;
}

export function GetFwStats200OkFromJSON(json: any): GetFwStats200Ok {
    return GetFwStats200OkFromJSONTyped(json, false);
}

export function GetFwStats200OkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFwStats200Ok {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'factionId': json['faction_id'],
        'kills': GetFwStatsKillsFromJSON(json['kills']),
        'pilots': json['pilots'],
        'systemsControlled': json['systems_controlled'],
        'victoryPoints': GetFwStatsVictoryPointsFromJSON(json['victory_points']),
    };
}

export function GetFwStats200OkToJSON(value?: GetFwStats200Ok | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'faction_id': value.factionId,
        'kills': GetFwStatsKillsToJSON(value.kills),
        'pilots': value.pilots,
        'systems_controlled': value.systemsControlled,
        'victory_points': GetFwStatsVictoryPointsToJSON(value.victoryPoints),
    };
}


