/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetFwLeaderboardsActiveTotalActiveTotal1,
    GetFwLeaderboardsActiveTotalActiveTotal1FromJSON,
    GetFwLeaderboardsActiveTotalActiveTotal1FromJSONTyped,
    GetFwLeaderboardsActiveTotalActiveTotal1ToJSON,
    GetFwLeaderboardsLastWeekLastWeek1,
    GetFwLeaderboardsLastWeekLastWeek1FromJSON,
    GetFwLeaderboardsLastWeekLastWeek1FromJSONTyped,
    GetFwLeaderboardsLastWeekLastWeek1ToJSON,
    GetFwLeaderboardsYesterdayYesterday1,
    GetFwLeaderboardsYesterdayYesterday1FromJSON,
    GetFwLeaderboardsYesterdayYesterday1FromJSONTyped,
    GetFwLeaderboardsYesterdayYesterday1ToJSON,
} from './';

/**
 * Top 4 rankings of factions by victory points from yesterday, last week and in total
 * @export
 * @interface GetFwLeaderboardsVictoryPoints
 */
export interface GetFwLeaderboardsVictoryPoints {
    /**
     * Top 4 ranking of factions active in faction warfare by total victory points. A faction is considered "active" if they have participated in faction warfare in the past 14 days
     * @type {Array<GetFwLeaderboardsActiveTotalActiveTotal1>}
     * @memberof GetFwLeaderboardsVictoryPoints
     */
    activeTotal: Array<GetFwLeaderboardsActiveTotalActiveTotal1>;
    /**
     * Top 4 ranking of factions by victory points in the past week
     * @type {Array<GetFwLeaderboardsLastWeekLastWeek1>}
     * @memberof GetFwLeaderboardsVictoryPoints
     */
    lastWeek: Array<GetFwLeaderboardsLastWeekLastWeek1>;
    /**
     * Top 4 ranking of factions by victory points in the past day
     * @type {Array<GetFwLeaderboardsYesterdayYesterday1>}
     * @memberof GetFwLeaderboardsVictoryPoints
     */
    yesterday: Array<GetFwLeaderboardsYesterdayYesterday1>;
}

export function GetFwLeaderboardsVictoryPointsFromJSON(json: any): GetFwLeaderboardsVictoryPoints {
    return GetFwLeaderboardsVictoryPointsFromJSONTyped(json, false);
}

export function GetFwLeaderboardsVictoryPointsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetFwLeaderboardsVictoryPoints {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'activeTotal': ((json['active_total'] as Array<any>).map(GetFwLeaderboardsActiveTotalActiveTotal1FromJSON)),
        'lastWeek': ((json['last_week'] as Array<any>).map(GetFwLeaderboardsLastWeekLastWeek1FromJSON)),
        'yesterday': ((json['yesterday'] as Array<any>).map(GetFwLeaderboardsYesterdayYesterday1FromJSON)),
    };
}

export function GetFwLeaderboardsVictoryPointsToJSON(value?: GetFwLeaderboardsVictoryPoints | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'active_total': ((value.activeTotal as Array<any>).map(GetFwLeaderboardsActiveTotalActiveTotal1ToJSON)),
        'last_week': ((value.lastWeek as Array<any>).map(GetFwLeaderboardsLastWeekLastWeek1ToJSON)),
        'yesterday': ((value.yesterday as Array<any>).map(GetFwLeaderboardsYesterdayYesterday1ToJSON)),
    };
}


