/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetInsurancePricesLevel,
    GetInsurancePricesLevelFromJSON,
    GetInsurancePricesLevelFromJSONTyped,
    GetInsurancePricesLevelToJSON,
} from './';

/**
 * 200 ok object
 * @export
 * @interface GetInsurancePrices200Ok
 */
export interface GetInsurancePrices200Ok {
    /**
     * A list of a available insurance levels for this ship type
     * @type {Array<GetInsurancePricesLevel>}
     * @memberof GetInsurancePrices200Ok
     */
    levels: Array<GetInsurancePricesLevel>;
    /**
     * type_id integer
     * @type {number}
     * @memberof GetInsurancePrices200Ok
     */
    typeId: number;
}

export function GetInsurancePrices200OkFromJSON(json: any): GetInsurancePrices200Ok {
    return GetInsurancePrices200OkFromJSONTyped(json, false);
}

export function GetInsurancePrices200OkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInsurancePrices200Ok {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'levels': ((json['levels'] as Array<any>).map(GetInsurancePricesLevelFromJSON)),
        'typeId': json['type_id'],
    };
}

export function GetInsurancePrices200OkToJSON(value?: GetInsurancePrices200Ok | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'levels': ((value.levels as Array<any>).map(GetInsurancePricesLevelToJSON)),
        'type_id': value.typeId,
    };
}


