/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 200 ok object
 * @export
 * @interface GetSearchOk
 */
export interface GetSearchOk {
    /**
     * agent array
     * @type {Array<number>}
     * @memberof GetSearchOk
     */
    agent?: Array<number>;
    /**
     * alliance array
     * @type {Array<number>}
     * @memberof GetSearchOk
     */
    alliance?: Array<number>;
    /**
     * character array
     * @type {Array<number>}
     * @memberof GetSearchOk
     */
    character?: Array<number>;
    /**
     * constellation array
     * @type {Array<number>}
     * @memberof GetSearchOk
     */
    constellation?: Array<number>;
    /**
     * corporation array
     * @type {Array<number>}
     * @memberof GetSearchOk
     */
    corporation?: Array<number>;
    /**
     * faction array
     * @type {Array<number>}
     * @memberof GetSearchOk
     */
    faction?: Array<number>;
    /**
     * inventory_type array
     * @type {Array<number>}
     * @memberof GetSearchOk
     */
    inventoryType?: Array<number>;
    /**
     * region array
     * @type {Array<number>}
     * @memberof GetSearchOk
     */
    region?: Array<number>;
    /**
     * solar_system array
     * @type {Array<number>}
     * @memberof GetSearchOk
     */
    solarSystem?: Array<number>;
    /**
     * station array
     * @type {Array<number>}
     * @memberof GetSearchOk
     */
    station?: Array<number>;
}

export function GetSearchOkFromJSON(json: any): GetSearchOk {
    return GetSearchOkFromJSONTyped(json, false);
}

export function GetSearchOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSearchOk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'agent': !exists(json, 'agent') ? undefined : json['agent'],
        'alliance': !exists(json, 'alliance') ? undefined : json['alliance'],
        'character': !exists(json, 'character') ? undefined : json['character'],
        'constellation': !exists(json, 'constellation') ? undefined : json['constellation'],
        'corporation': !exists(json, 'corporation') ? undefined : json['corporation'],
        'faction': !exists(json, 'faction') ? undefined : json['faction'],
        'inventoryType': !exists(json, 'inventory_type') ? undefined : json['inventory_type'],
        'region': !exists(json, 'region') ? undefined : json['region'],
        'solarSystem': !exists(json, 'solar_system') ? undefined : json['solar_system'],
        'station': !exists(json, 'station') ? undefined : json['station'],
    };
}

export function GetSearchOkToJSON(value?: GetSearchOk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'agent': value.agent,
        'alliance': value.alliance,
        'character': value.character,
        'constellation': value.constellation,
        'corporation': value.corporation,
        'faction': value.faction,
        'inventory_type': value.inventoryType,
        'region': value.region,
        'solar_system': value.solarSystem,
        'station': value.station,
    };
}


