/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * position object
 * @export
 * @interface GetUniverseSystemsSystemIdPosition
 */
export interface GetUniverseSystemsSystemIdPosition {
    /**
     * x number
     * @type {number}
     * @memberof GetUniverseSystemsSystemIdPosition
     */
    x: number;
    /**
     * y number
     * @type {number}
     * @memberof GetUniverseSystemsSystemIdPosition
     */
    y: number;
    /**
     * z number
     * @type {number}
     * @memberof GetUniverseSystemsSystemIdPosition
     */
    z: number;
}

export function GetUniverseSystemsSystemIdPositionFromJSON(json: any): GetUniverseSystemsSystemIdPosition {
    return GetUniverseSystemsSystemIdPositionFromJSONTyped(json, false);
}

export function GetUniverseSystemsSystemIdPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUniverseSystemsSystemIdPosition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
        'z': json['z'],
    };
}

export function GetUniverseSystemsSystemIdPositionToJSON(value?: GetUniverseSystemsSystemIdPosition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'x': value.x,
        'y': value.y,
        'z': value.z,
    };
}


