/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 200 ok object
 * @export
 * @interface GetUniverseSchematicsSchematicIdOk
 */
export interface GetUniverseSchematicsSchematicIdOk {
    /**
     * Time in seconds to process a run
     * @type {number}
     * @memberof GetUniverseSchematicsSchematicIdOk
     */
    cycleTime: number;
    /**
     * schematic_name string
     * @type {string}
     * @memberof GetUniverseSchematicsSchematicIdOk
     */
    schematicName: string;
}

export function GetUniverseSchematicsSchematicIdOkFromJSON(json: any): GetUniverseSchematicsSchematicIdOk {
    return GetUniverseSchematicsSchematicIdOkFromJSONTyped(json, false);
}

export function GetUniverseSchematicsSchematicIdOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUniverseSchematicsSchematicIdOk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cycleTime': json['cycle_time'],
        'schematicName': json['schematic_name'],
    };
}

export function GetUniverseSchematicsSchematicIdOkToJSON(value?: GetUniverseSchematicsSchematicIdOk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cycle_time': value.cycleTime,
        'schematic_name': value.schematicName,
    };
}


