/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetUniverseMoonsMoonIdPosition,
    GetUniverseMoonsMoonIdPositionFromJSON,
    GetUniverseMoonsMoonIdPositionFromJSONTyped,
    GetUniverseMoonsMoonIdPositionToJSON,
} from './';

/**
 * 200 ok object
 * @export
 * @interface GetUniverseMoonsMoonIdOk
 */
export interface GetUniverseMoonsMoonIdOk {
    /**
     * moon_id integer
     * @type {number}
     * @memberof GetUniverseMoonsMoonIdOk
     */
    moonId: number;
    /**
     * name string
     * @type {string}
     * @memberof GetUniverseMoonsMoonIdOk
     */
    name: string;
    /**
     * 
     * @type {GetUniverseMoonsMoonIdPosition}
     * @memberof GetUniverseMoonsMoonIdOk
     */
    position: GetUniverseMoonsMoonIdPosition;
    /**
     * The solar system this moon is in
     * @type {number}
     * @memberof GetUniverseMoonsMoonIdOk
     */
    systemId: number;
}

export function GetUniverseMoonsMoonIdOkFromJSON(json: any): GetUniverseMoonsMoonIdOk {
    return GetUniverseMoonsMoonIdOkFromJSONTyped(json, false);
}

export function GetUniverseMoonsMoonIdOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUniverseMoonsMoonIdOk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'moonId': json['moon_id'],
        'name': json['name'],
        'position': GetUniverseMoonsMoonIdPositionFromJSON(json['position']),
        'systemId': json['system_id'],
    };
}

export function GetUniverseMoonsMoonIdOkToJSON(value?: GetUniverseMoonsMoonIdOk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'moon_id': value.moonId,
        'name': value.name,
        'position': GetUniverseMoonsMoonIdPositionToJSON(value.position),
        'system_id': value.systemId,
    };
}


