/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetUniverseConstellationsConstellationIdPosition,
    GetUniverseConstellationsConstellationIdPositionFromJSON,
    GetUniverseConstellationsConstellationIdPositionFromJSONTyped,
    GetUniverseConstellationsConstellationIdPositionToJSON,
} from './';

/**
 * 200 ok object
 * @export
 * @interface GetUniverseConstellationsConstellationIdOk
 */
export interface GetUniverseConstellationsConstellationIdOk {
    /**
     * constellation_id integer
     * @type {number}
     * @memberof GetUniverseConstellationsConstellationIdOk
     */
    constellationId: number;
    /**
     * name string
     * @type {string}
     * @memberof GetUniverseConstellationsConstellationIdOk
     */
    name: string;
    /**
     * 
     * @type {GetUniverseConstellationsConstellationIdPosition}
     * @memberof GetUniverseConstellationsConstellationIdOk
     */
    position: GetUniverseConstellationsConstellationIdPosition;
    /**
     * The region this constellation is in
     * @type {number}
     * @memberof GetUniverseConstellationsConstellationIdOk
     */
    regionId: number;
    /**
     * systems array
     * @type {Array<number>}
     * @memberof GetUniverseConstellationsConstellationIdOk
     */
    systems: Array<number>;
}

export function GetUniverseConstellationsConstellationIdOkFromJSON(json: any): GetUniverseConstellationsConstellationIdOk {
    return GetUniverseConstellationsConstellationIdOkFromJSONTyped(json, false);
}

export function GetUniverseConstellationsConstellationIdOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUniverseConstellationsConstellationIdOk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'constellationId': json['constellation_id'],
        'name': json['name'],
        'position': GetUniverseConstellationsConstellationIdPositionFromJSON(json['position']),
        'regionId': json['region_id'],
        'systems': json['systems'],
    };
}

export function GetUniverseConstellationsConstellationIdOkToJSON(value?: GetUniverseConstellationsConstellationIdOk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'constellation_id': value.constellationId,
        'name': value.name,
        'position': GetUniverseConstellationsConstellationIdPositionToJSON(value.position),
        'region_id': value.regionId,
        'systems': value.systems,
    };
}


