/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetUniversePlanetsPlanetIdPosition,
    GetUniversePlanetsPlanetIdPositionFromJSON,
    GetUniversePlanetsPlanetIdPositionFromJSONTyped,
    GetUniversePlanetsPlanetIdPositionToJSON,
} from './';

/**
 * 200 ok object
 * @export
 * @interface GetUniversePlanetsPlanetIdOk
 */
export interface GetUniversePlanetsPlanetIdOk {
    /**
     * name string
     * @type {string}
     * @memberof GetUniversePlanetsPlanetIdOk
     */
    name: string;
    /**
     * planet_id integer
     * @type {number}
     * @memberof GetUniversePlanetsPlanetIdOk
     */
    planetId: number;
    /**
     * 
     * @type {GetUniversePlanetsPlanetIdPosition}
     * @memberof GetUniversePlanetsPlanetIdOk
     */
    position: GetUniversePlanetsPlanetIdPosition;
    /**
     * The solar system this planet is in
     * @type {number}
     * @memberof GetUniversePlanetsPlanetIdOk
     */
    systemId: number;
    /**
     * type_id integer
     * @type {number}
     * @memberof GetUniversePlanetsPlanetIdOk
     */
    typeId: number;
}

export function GetUniversePlanetsPlanetIdOkFromJSON(json: any): GetUniversePlanetsPlanetIdOk {
    return GetUniversePlanetsPlanetIdOkFromJSONTyped(json, false);
}

export function GetUniversePlanetsPlanetIdOkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUniversePlanetsPlanetIdOk {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'planetId': json['planet_id'],
        'position': GetUniversePlanetsPlanetIdPositionFromJSON(json['position']),
        'systemId': json['system_id'],
        'typeId': json['type_id'],
    };
}

export function GetUniversePlanetsPlanetIdOkToJSON(value?: GetUniversePlanetsPlanetIdOk | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'planet_id': value.planetId,
        'position': GetUniversePlanetsPlanetIdPositionToJSON(value.position),
        'system_id': value.systemId,
        'type_id': value.typeId,
    };
}


