/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Not found
 * @export
 * @interface GetUniverseMoonsMoonIdNotFound
 */
export interface GetUniverseMoonsMoonIdNotFound {
    /**
     * Not found message
     * @type {string}
     * @memberof GetUniverseMoonsMoonIdNotFound
     */
    error?: string;
}

export function GetUniverseMoonsMoonIdNotFoundFromJSON(json: any): GetUniverseMoonsMoonIdNotFound {
    return GetUniverseMoonsMoonIdNotFoundFromJSONTyped(json, false);
}

export function GetUniverseMoonsMoonIdNotFoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUniverseMoonsMoonIdNotFound {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function GetUniverseMoonsMoonIdNotFoundToJSON(value?: GetUniverseMoonsMoonIdNotFound | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}


