/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * response object
 * @export
 * @interface PutCharactersCharacterIdCalendarEventIdResponse
 */
export interface PutCharactersCharacterIdCalendarEventIdResponse {
    /**
     * response string
     * @type {string}
     * @memberof PutCharactersCharacterIdCalendarEventIdResponse
     */
    response: PutCharactersCharacterIdCalendarEventIdResponseResponseEnum;
}

export function PutCharactersCharacterIdCalendarEventIdResponseFromJSON(json: any): PutCharactersCharacterIdCalendarEventIdResponse {
    return PutCharactersCharacterIdCalendarEventIdResponseFromJSONTyped(json, false);
}

export function PutCharactersCharacterIdCalendarEventIdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutCharactersCharacterIdCalendarEventIdResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': json['response'],
    };
}

export function PutCharactersCharacterIdCalendarEventIdResponseToJSON(value?: PutCharactersCharacterIdCalendarEventIdResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': value.response,
    };
}

/**
* @export
* @enum {string}
*/
export enum PutCharactersCharacterIdCalendarEventIdResponseResponseEnum {
    Accepted = 'accepted',
    Declined = 'declined',
    Tentative = 'tentative'
}


