/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Unauthorized model
 * @export
 * @interface Unauthorized
 */
export interface Unauthorized {
    /**
     * Unauthorized message
     * @type {string}
     * @memberof Unauthorized
     */
    error: string;
}

export function UnauthorizedFromJSON(json: any): Unauthorized {
    return UnauthorizedFromJSONTyped(json, false);
}

export function UnauthorizedFromJSONTyped(json: any, ignoreDiscriminator: boolean): Unauthorized {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function UnauthorizedToJSON(value?: Unauthorized | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}


