/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BadRequest,
    BadRequestFromJSON,
    BadRequestToJSON,
    ErrorLimited,
    ErrorLimitedFromJSON,
    ErrorLimitedToJSON,
    GatewayTimeout,
    GatewayTimeoutFromJSON,
    GatewayTimeoutToJSON,
    GetAlliancesAllianceIdIconsNotFound,
    GetAlliancesAllianceIdIconsNotFoundFromJSON,
    GetAlliancesAllianceIdIconsNotFoundToJSON,
    GetAlliancesAllianceIdIconsOk,
    GetAlliancesAllianceIdIconsOkFromJSON,
    GetAlliancesAllianceIdIconsOkToJSON,
    GetAlliancesAllianceIdNotFound,
    GetAlliancesAllianceIdNotFoundFromJSON,
    GetAlliancesAllianceIdNotFoundToJSON,
    GetAlliancesAllianceIdOk,
    GetAlliancesAllianceIdOkFromJSON,
    GetAlliancesAllianceIdOkToJSON,
    InternalServerError,
    InternalServerErrorFromJSON,
    InternalServerErrorToJSON,
    ServiceUnavailable,
    ServiceUnavailableFromJSON,
    ServiceUnavailableToJSON,
} from '../models';

export interface GetAlliancesRequest {
    datasource?: GetAlliancesDatasourceEnum;
    ifNoneMatch?: string;
}

export interface GetAlliancesAllianceIdRequest {
    allianceId: number;
    datasource?: GetAlliancesAllianceIdDatasourceEnum;
    ifNoneMatch?: string;
}

export interface GetAlliancesAllianceIdCorporationsRequest {
    allianceId: number;
    datasource?: GetAlliancesAllianceIdCorporationsDatasourceEnum;
    ifNoneMatch?: string;
}

export interface GetAlliancesAllianceIdIconsRequest {
    allianceId: number;
    datasource?: GetAlliancesAllianceIdIconsDatasourceEnum;
    ifNoneMatch?: string;
}

/**
 * 
 */
export class AllianceApi extends runtime.BaseAPI {

    /**
     * List all active player alliances  --- Alternate route: `/dev/alliances/`  Alternate route: `/legacy/alliances/`  Alternate route: `/v1/alliances/`  Alternate route: `/v2/alliances/`  --- This route is cached for up to 3600 seconds
     * List all alliances
     */
    async getAlliancesRaw(requestParameters: GetAlliancesRequest): Promise<runtime.ApiResponse<Array<number>>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.datasource !== undefined) {
            queryParameters['datasource'] = requestParameters.datasource;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.ifNoneMatch !== undefined && requestParameters.ifNoneMatch !== null) {
            headerParameters['If-None-Match'] = String(requestParameters.ifNoneMatch);
        }

        const response = await this.request({
            path: `/alliances/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List all active player alliances  --- Alternate route: `/dev/alliances/`  Alternate route: `/legacy/alliances/`  Alternate route: `/v1/alliances/`  Alternate route: `/v2/alliances/`  --- This route is cached for up to 3600 seconds
     * List all alliances
     */
    async getAlliances(requestParameters: GetAlliancesRequest): Promise<Array<number>> {
        const response = await this.getAlliancesRaw(requestParameters);
        return await response.value();
    }

    /**
     * Public information about an alliance  --- Alternate route: `/dev/alliances/{alliance_id}/`  Alternate route: `/legacy/alliances/{alliance_id}/`  Alternate route: `/v3/alliances/{alliance_id}/`  Alternate route: `/v4/alliances/{alliance_id}/`  --- This route is cached for up to 3600 seconds
     * Get alliance information
     */
    async getAlliancesAllianceIdRaw(requestParameters: GetAlliancesAllianceIdRequest): Promise<runtime.ApiResponse<GetAlliancesAllianceIdOk>> {
        if (requestParameters.allianceId === null || requestParameters.allianceId === undefined) {
            throw new runtime.RequiredError('allianceId','Required parameter requestParameters.allianceId was null or undefined when calling getAlliancesAllianceId.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.datasource !== undefined) {
            queryParameters['datasource'] = requestParameters.datasource;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.ifNoneMatch !== undefined && requestParameters.ifNoneMatch !== null) {
            headerParameters['If-None-Match'] = String(requestParameters.ifNoneMatch);
        }

        const response = await this.request({
            path: `/alliances/{alliance_id}/`.replace(`{${"alliance_id"}}`, encodeURIComponent(String(requestParameters.allianceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAlliancesAllianceIdOkFromJSON(jsonValue));
    }

    /**
     * Public information about an alliance  --- Alternate route: `/dev/alliances/{alliance_id}/`  Alternate route: `/legacy/alliances/{alliance_id}/`  Alternate route: `/v3/alliances/{alliance_id}/`  Alternate route: `/v4/alliances/{alliance_id}/`  --- This route is cached for up to 3600 seconds
     * Get alliance information
     */
    async getAlliancesAllianceId(requestParameters: GetAlliancesAllianceIdRequest): Promise<GetAlliancesAllianceIdOk> {
        const response = await this.getAlliancesAllianceIdRaw(requestParameters);
        return await response.value();
    }

    /**
     * List all current member corporations of an alliance  --- Alternate route: `/dev/alliances/{alliance_id}/corporations/`  Alternate route: `/legacy/alliances/{alliance_id}/corporations/`  Alternate route: `/v1/alliances/{alliance_id}/corporations/`  Alternate route: `/v2/alliances/{alliance_id}/corporations/`  --- This route is cached for up to 3600 seconds
     * List alliance\'s corporations
     */
    async getAlliancesAllianceIdCorporationsRaw(requestParameters: GetAlliancesAllianceIdCorporationsRequest): Promise<runtime.ApiResponse<Array<number>>> {
        if (requestParameters.allianceId === null || requestParameters.allianceId === undefined) {
            throw new runtime.RequiredError('allianceId','Required parameter requestParameters.allianceId was null or undefined when calling getAlliancesAllianceIdCorporations.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.datasource !== undefined) {
            queryParameters['datasource'] = requestParameters.datasource;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.ifNoneMatch !== undefined && requestParameters.ifNoneMatch !== null) {
            headerParameters['If-None-Match'] = String(requestParameters.ifNoneMatch);
        }

        const response = await this.request({
            path: `/alliances/{alliance_id}/corporations/`.replace(`{${"alliance_id"}}`, encodeURIComponent(String(requestParameters.allianceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * List all current member corporations of an alliance  --- Alternate route: `/dev/alliances/{alliance_id}/corporations/`  Alternate route: `/legacy/alliances/{alliance_id}/corporations/`  Alternate route: `/v1/alliances/{alliance_id}/corporations/`  Alternate route: `/v2/alliances/{alliance_id}/corporations/`  --- This route is cached for up to 3600 seconds
     * List alliance\'s corporations
     */
    async getAlliancesAllianceIdCorporations(requestParameters: GetAlliancesAllianceIdCorporationsRequest): Promise<Array<number>> {
        const response = await this.getAlliancesAllianceIdCorporationsRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get the icon urls for a alliance  --- Alternate route: `/legacy/alliances/{alliance_id}/icons/`  Alternate route: `/v1/alliances/{alliance_id}/icons/`  --- This route expires daily at 11:05  --- [Diff of the upcoming changes](https://esi.evepc.163.com/diff/latest/dev/#GET-/alliances/{alliance_id}/icons/)
     * Get alliance icon
     */
    async getAlliancesAllianceIdIconsRaw(requestParameters: GetAlliancesAllianceIdIconsRequest): Promise<runtime.ApiResponse<GetAlliancesAllianceIdIconsOk>> {
        if (requestParameters.allianceId === null || requestParameters.allianceId === undefined) {
            throw new runtime.RequiredError('allianceId','Required parameter requestParameters.allianceId was null or undefined when calling getAlliancesAllianceIdIcons.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.datasource !== undefined) {
            queryParameters['datasource'] = requestParameters.datasource;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.ifNoneMatch !== undefined && requestParameters.ifNoneMatch !== null) {
            headerParameters['If-None-Match'] = String(requestParameters.ifNoneMatch);
        }

        const response = await this.request({
            path: `/alliances/{alliance_id}/icons/`.replace(`{${"alliance_id"}}`, encodeURIComponent(String(requestParameters.allianceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAlliancesAllianceIdIconsOkFromJSON(jsonValue));
    }

    /**
     * Get the icon urls for a alliance  --- Alternate route: `/legacy/alliances/{alliance_id}/icons/`  Alternate route: `/v1/alliances/{alliance_id}/icons/`  --- This route expires daily at 11:05  --- [Diff of the upcoming changes](https://esi.evepc.163.com/diff/latest/dev/#GET-/alliances/{alliance_id}/icons/)
     * Get alliance icon
     */
    async getAlliancesAllianceIdIcons(requestParameters: GetAlliancesAllianceIdIconsRequest): Promise<GetAlliancesAllianceIdIconsOk> {
        const response = await this.getAlliancesAllianceIdIconsRaw(requestParameters);
        return await response.value();
    }

}

/**
    * @export
    * @enum {string}
    */
export enum GetAlliancesDatasourceEnum {
    Serenity = 'serenity'
}
/**
    * @export
    * @enum {string}
    */
export enum GetAlliancesAllianceIdDatasourceEnum {
    Serenity = 'serenity'
}
/**
    * @export
    * @enum {string}
    */
export enum GetAlliancesAllianceIdCorporationsDatasourceEnum {
    Serenity = 'serenity'
}
/**
    * @export
    * @enum {string}
    */
export enum GetAlliancesAllianceIdIconsDatasourceEnum {
    Serenity = 'serenity'
}
