/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BadRequest,
    BadRequestFromJSON,
    BadRequestToJSON,
    ErrorLimited,
    ErrorLimitedFromJSON,
    ErrorLimitedToJSON,
    Forbidden,
    ForbiddenFromJSON,
    ForbiddenToJSON,
    GatewayTimeout,
    GatewayTimeoutFromJSON,
    GatewayTimeoutToJSON,
    GetCharactersCharacterIdBookmarks200Ok,
    GetCharactersCharacterIdBookmarks200OkFromJSON,
    GetCharactersCharacterIdBookmarks200OkToJSON,
    GetCharactersCharacterIdBookmarksFolders200Ok,
    GetCharactersCharacterIdBookmarksFolders200OkFromJSON,
    GetCharactersCharacterIdBookmarksFolders200OkToJSON,
    GetCorporationsCorporationIdBookmarks200Ok,
    GetCorporationsCorporationIdBookmarks200OkFromJSON,
    GetCorporationsCorporationIdBookmarks200OkToJSON,
    GetCorporationsCorporationIdBookmarksFolders200Ok,
    GetCorporationsCorporationIdBookmarksFolders200OkFromJSON,
    GetCorporationsCorporationIdBookmarksFolders200OkToJSON,
    InternalServerError,
    InternalServerErrorFromJSON,
    InternalServerErrorToJSON,
    ServiceUnavailable,
    ServiceUnavailableFromJSON,
    ServiceUnavailableToJSON,
    Unauthorized,
    UnauthorizedFromJSON,
    UnauthorizedToJSON,
} from '../models';

export interface GetCharactersCharacterIdBookmarksRequest {
    characterId: number;
    datasource?: GetCharactersCharacterIdBookmarksDatasourceEnum;
    ifNoneMatch?: string;
    page?: number;
    token?: string;
}

export interface GetCharactersCharacterIdBookmarksFoldersRequest {
    characterId: number;
    datasource?: GetCharactersCharacterIdBookmarksFoldersDatasourceEnum;
    ifNoneMatch?: string;
    page?: number;
    token?: string;
}

export interface GetCorporationsCorporationIdBookmarksRequest {
    corporationId: number;
    datasource?: GetCorporationsCorporationIdBookmarksDatasourceEnum;
    ifNoneMatch?: string;
    page?: number;
    token?: string;
}

export interface GetCorporationsCorporationIdBookmarksFoldersRequest {
    corporationId: number;
    datasource?: GetCorporationsCorporationIdBookmarksFoldersDatasourceEnum;
    ifNoneMatch?: string;
    page?: number;
    token?: string;
}

/**
 * 
 */
export class BookmarksApi extends runtime.BaseAPI {

    /**
     * A list of your character\'s personal bookmarks  --- Alternate route: `/dev/characters/{character_id}/bookmarks/`  Alternate route: `/v2/characters/{character_id}/bookmarks/`  --- This route is cached for up to 3600 seconds
     * List bookmarks
     */
    async getCharactersCharacterIdBookmarksRaw(requestParameters: GetCharactersCharacterIdBookmarksRequest): Promise<runtime.ApiResponse<Array<GetCharactersCharacterIdBookmarks200Ok>>> {
        if (requestParameters.characterId === null || requestParameters.characterId === undefined) {
            throw new runtime.RequiredError('characterId','Required parameter requestParameters.characterId was null or undefined when calling getCharactersCharacterIdBookmarks.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.datasource !== undefined) {
            queryParameters['datasource'] = requestParameters.datasource;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.token !== undefined) {
            queryParameters['token'] = requestParameters.token;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.ifNoneMatch !== undefined && requestParameters.ifNoneMatch !== null) {
            headerParameters['If-None-Match'] = String(requestParameters.ifNoneMatch);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("evesso", ["esi-bookmarks.read_character_bookmarks.v1"]);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/characters/{character_id}/bookmarks/`.replace(`{${"character_id"}}`, encodeURIComponent(String(requestParameters.characterId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetCharactersCharacterIdBookmarks200OkFromJSON));
    }

    /**
     * A list of your character\'s personal bookmarks  --- Alternate route: `/dev/characters/{character_id}/bookmarks/`  Alternate route: `/v2/characters/{character_id}/bookmarks/`  --- This route is cached for up to 3600 seconds
     * List bookmarks
     */
    async getCharactersCharacterIdBookmarks(requestParameters: GetCharactersCharacterIdBookmarksRequest): Promise<Array<GetCharactersCharacterIdBookmarks200Ok>> {
        const response = await this.getCharactersCharacterIdBookmarksRaw(requestParameters);
        return await response.value();
    }

    /**
     * A list of your character\'s personal bookmark folders  --- Alternate route: `/dev/characters/{character_id}/bookmarks/folders/`  Alternate route: `/v2/characters/{character_id}/bookmarks/folders/`  --- This route is cached for up to 3600 seconds
     * List bookmark folders
     */
    async getCharactersCharacterIdBookmarksFoldersRaw(requestParameters: GetCharactersCharacterIdBookmarksFoldersRequest): Promise<runtime.ApiResponse<Array<GetCharactersCharacterIdBookmarksFolders200Ok>>> {
        if (requestParameters.characterId === null || requestParameters.characterId === undefined) {
            throw new runtime.RequiredError('characterId','Required parameter requestParameters.characterId was null or undefined when calling getCharactersCharacterIdBookmarksFolders.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.datasource !== undefined) {
            queryParameters['datasource'] = requestParameters.datasource;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.token !== undefined) {
            queryParameters['token'] = requestParameters.token;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.ifNoneMatch !== undefined && requestParameters.ifNoneMatch !== null) {
            headerParameters['If-None-Match'] = String(requestParameters.ifNoneMatch);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("evesso", ["esi-bookmarks.read_character_bookmarks.v1"]);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/characters/{character_id}/bookmarks/folders/`.replace(`{${"character_id"}}`, encodeURIComponent(String(requestParameters.characterId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetCharactersCharacterIdBookmarksFolders200OkFromJSON));
    }

    /**
     * A list of your character\'s personal bookmark folders  --- Alternate route: `/dev/characters/{character_id}/bookmarks/folders/`  Alternate route: `/v2/characters/{character_id}/bookmarks/folders/`  --- This route is cached for up to 3600 seconds
     * List bookmark folders
     */
    async getCharactersCharacterIdBookmarksFolders(requestParameters: GetCharactersCharacterIdBookmarksFoldersRequest): Promise<Array<GetCharactersCharacterIdBookmarksFolders200Ok>> {
        const response = await this.getCharactersCharacterIdBookmarksFoldersRaw(requestParameters);
        return await response.value();
    }

    /**
     * A list of your corporation\'s bookmarks  --- Alternate route: `/dev/corporations/{corporation_id}/bookmarks/`  Alternate route: `/legacy/corporations/{corporation_id}/bookmarks/`  Alternate route: `/v1/corporations/{corporation_id}/bookmarks/`  --- This route is cached for up to 3600 seconds
     * List corporation bookmarks
     */
    async getCorporationsCorporationIdBookmarksRaw(requestParameters: GetCorporationsCorporationIdBookmarksRequest): Promise<runtime.ApiResponse<Array<GetCorporationsCorporationIdBookmarks200Ok>>> {
        if (requestParameters.corporationId === null || requestParameters.corporationId === undefined) {
            throw new runtime.RequiredError('corporationId','Required parameter requestParameters.corporationId was null or undefined when calling getCorporationsCorporationIdBookmarks.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.datasource !== undefined) {
            queryParameters['datasource'] = requestParameters.datasource;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.token !== undefined) {
            queryParameters['token'] = requestParameters.token;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.ifNoneMatch !== undefined && requestParameters.ifNoneMatch !== null) {
            headerParameters['If-None-Match'] = String(requestParameters.ifNoneMatch);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("evesso", ["esi-bookmarks.read_corporation_bookmarks.v1"]);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/corporations/{corporation_id}/bookmarks/`.replace(`{${"corporation_id"}}`, encodeURIComponent(String(requestParameters.corporationId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetCorporationsCorporationIdBookmarks200OkFromJSON));
    }

    /**
     * A list of your corporation\'s bookmarks  --- Alternate route: `/dev/corporations/{corporation_id}/bookmarks/`  Alternate route: `/legacy/corporations/{corporation_id}/bookmarks/`  Alternate route: `/v1/corporations/{corporation_id}/bookmarks/`  --- This route is cached for up to 3600 seconds
     * List corporation bookmarks
     */
    async getCorporationsCorporationIdBookmarks(requestParameters: GetCorporationsCorporationIdBookmarksRequest): Promise<Array<GetCorporationsCorporationIdBookmarks200Ok>> {
        const response = await this.getCorporationsCorporationIdBookmarksRaw(requestParameters);
        return await response.value();
    }

    /**
     * A list of your corporation\'s bookmark folders  --- Alternate route: `/dev/corporations/{corporation_id}/bookmarks/folders/`  Alternate route: `/legacy/corporations/{corporation_id}/bookmarks/folders/`  Alternate route: `/v1/corporations/{corporation_id}/bookmarks/folders/`  --- This route is cached for up to 3600 seconds
     * List corporation bookmark folders
     */
    async getCorporationsCorporationIdBookmarksFoldersRaw(requestParameters: GetCorporationsCorporationIdBookmarksFoldersRequest): Promise<runtime.ApiResponse<Array<GetCorporationsCorporationIdBookmarksFolders200Ok>>> {
        if (requestParameters.corporationId === null || requestParameters.corporationId === undefined) {
            throw new runtime.RequiredError('corporationId','Required parameter requestParameters.corporationId was null or undefined when calling getCorporationsCorporationIdBookmarksFolders.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.datasource !== undefined) {
            queryParameters['datasource'] = requestParameters.datasource;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.token !== undefined) {
            queryParameters['token'] = requestParameters.token;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.ifNoneMatch !== undefined && requestParameters.ifNoneMatch !== null) {
            headerParameters['If-None-Match'] = String(requestParameters.ifNoneMatch);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("evesso", ["esi-bookmarks.read_corporation_bookmarks.v1"]);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/corporations/{corporation_id}/bookmarks/folders/`.replace(`{${"corporation_id"}}`, encodeURIComponent(String(requestParameters.corporationId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetCorporationsCorporationIdBookmarksFolders200OkFromJSON));
    }

    /**
     * A list of your corporation\'s bookmark folders  --- Alternate route: `/dev/corporations/{corporation_id}/bookmarks/folders/`  Alternate route: `/legacy/corporations/{corporation_id}/bookmarks/folders/`  Alternate route: `/v1/corporations/{corporation_id}/bookmarks/folders/`  --- This route is cached for up to 3600 seconds
     * List corporation bookmark folders
     */
    async getCorporationsCorporationIdBookmarksFolders(requestParameters: GetCorporationsCorporationIdBookmarksFoldersRequest): Promise<Array<GetCorporationsCorporationIdBookmarksFolders200Ok>> {
        const response = await this.getCorporationsCorporationIdBookmarksFoldersRaw(requestParameters);
        return await response.value();
    }

}

/**
    * @export
    * @enum {string}
    */
export enum GetCharactersCharacterIdBookmarksDatasourceEnum {
    Serenity = 'serenity'
}
/**
    * @export
    * @enum {string}
    */
export enum GetCharactersCharacterIdBookmarksFoldersDatasourceEnum {
    Serenity = 'serenity'
}
/**
    * @export
    * @enum {string}
    */
export enum GetCorporationsCorporationIdBookmarksDatasourceEnum {
    Serenity = 'serenity'
}
/**
    * @export
    * @enum {string}
    */
export enum GetCorporationsCorporationIdBookmarksFoldersDatasourceEnum {
    Serenity = 'serenity'
}
