/* tslint:disable */
/* eslint-disable */
/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.7.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BadRequest,
    BadRequestFromJSON,
    BadRequestToJSON,
    ErrorLimited,
    ErrorLimitedFromJSON,
    ErrorLimitedToJSON,
    Forbidden,
    ForbiddenFromJSON,
    ForbiddenToJSON,
    GatewayTimeout,
    GatewayTimeoutFromJSON,
    GatewayTimeoutToJSON,
    GetCharactersCharacterIdSearchOk,
    GetCharactersCharacterIdSearchOkFromJSON,
    GetCharactersCharacterIdSearchOkToJSON,
    GetSearchOk,
    GetSearchOkFromJSON,
    GetSearchOkToJSON,
    InternalServerError,
    InternalServerErrorFromJSON,
    InternalServerErrorToJSON,
    ServiceUnavailable,
    ServiceUnavailableFromJSON,
    ServiceUnavailableToJSON,
    Unauthorized,
    UnauthorizedFromJSON,
    UnauthorizedToJSON,
} from '../models';

export interface GetCharactersCharacterIdSearchRequest {
    categories: Array<GetCharactersCharacterIdSearchCategoriesEnum>;
    characterId: number;
    search: string;
    acceptLanguage?: GetCharactersCharacterIdSearchAcceptLanguageEnum;
    datasource?: GetCharactersCharacterIdSearchDatasourceEnum;
    ifNoneMatch?: string;
    language?: GetCharactersCharacterIdSearchLanguageEnum;
    strict?: boolean;
    token?: string;
}

export interface GetSearchRequest {
    categories: Array<GetSearchCategoriesEnum>;
    search: string;
    acceptLanguage?: GetSearchAcceptLanguageEnum;
    datasource?: GetSearchDatasourceEnum;
    ifNoneMatch?: string;
    language?: GetSearchLanguageEnum;
    strict?: boolean;
}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI {

    /**
     * Search for entities that match a given sub-string.  --- Alternate route: `/dev/characters/{character_id}/search/`  Alternate route: `/legacy/characters/{character_id}/search/`  Alternate route: `/v3/characters/{character_id}/search/`  --- This route is cached for up to 3600 seconds
     * Search on a string
     */
    async getCharactersCharacterIdSearchRaw(requestParameters: GetCharactersCharacterIdSearchRequest): Promise<runtime.ApiResponse<GetCharactersCharacterIdSearchOk>> {
        if (requestParameters.categories === null || requestParameters.categories === undefined) {
            throw new runtime.RequiredError('categories','Required parameter requestParameters.categories was null or undefined when calling getCharactersCharacterIdSearch.');
        }

        if (requestParameters.characterId === null || requestParameters.characterId === undefined) {
            throw new runtime.RequiredError('characterId','Required parameter requestParameters.characterId was null or undefined when calling getCharactersCharacterIdSearch.');
        }

        if (requestParameters.search === null || requestParameters.search === undefined) {
            throw new runtime.RequiredError('search','Required parameter requestParameters.search was null or undefined when calling getCharactersCharacterIdSearch.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.categories) {
            queryParameters['categories'] = requestParameters.categories.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.datasource !== undefined) {
            queryParameters['datasource'] = requestParameters.datasource;
        }

        if (requestParameters.language !== undefined) {
            queryParameters['language'] = requestParameters.language;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        if (requestParameters.strict !== undefined) {
            queryParameters['strict'] = requestParameters.strict;
        }

        if (requestParameters.token !== undefined) {
            queryParameters['token'] = requestParameters.token;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.acceptLanguage !== undefined && requestParameters.acceptLanguage !== null) {
            headerParameters['Accept-Language'] = String(requestParameters.acceptLanguage);
        }

        if (requestParameters.ifNoneMatch !== undefined && requestParameters.ifNoneMatch !== null) {
            headerParameters['If-None-Match'] = String(requestParameters.ifNoneMatch);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("evesso", ["esi-search.search_structures.v1"]);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/characters/{character_id}/search/`.replace(`{${"character_id"}}`, encodeURIComponent(String(requestParameters.characterId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCharactersCharacterIdSearchOkFromJSON(jsonValue));
    }

    /**
     * Search for entities that match a given sub-string.  --- Alternate route: `/dev/characters/{character_id}/search/`  Alternate route: `/legacy/characters/{character_id}/search/`  Alternate route: `/v3/characters/{character_id}/search/`  --- This route is cached for up to 3600 seconds
     * Search on a string
     */
    async getCharactersCharacterIdSearch(requestParameters: GetCharactersCharacterIdSearchRequest): Promise<GetCharactersCharacterIdSearchOk> {
        const response = await this.getCharactersCharacterIdSearchRaw(requestParameters);
        return await response.value();
    }

    /**
     * Search for entities that match a given sub-string.  --- Alternate route: `/dev/search/`  Alternate route: `/legacy/search/`  Alternate route: `/v2/search/`  --- This route is cached for up to 3600 seconds
     * Search on a string
     */
    async getSearchRaw(requestParameters: GetSearchRequest): Promise<runtime.ApiResponse<GetSearchOk>> {
        if (requestParameters.categories === null || requestParameters.categories === undefined) {
            throw new runtime.RequiredError('categories','Required parameter requestParameters.categories was null or undefined when calling getSearch.');
        }

        if (requestParameters.search === null || requestParameters.search === undefined) {
            throw new runtime.RequiredError('search','Required parameter requestParameters.search was null or undefined when calling getSearch.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.categories) {
            queryParameters['categories'] = requestParameters.categories.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters.datasource !== undefined) {
            queryParameters['datasource'] = requestParameters.datasource;
        }

        if (requestParameters.language !== undefined) {
            queryParameters['language'] = requestParameters.language;
        }

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        if (requestParameters.strict !== undefined) {
            queryParameters['strict'] = requestParameters.strict;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.acceptLanguage !== undefined && requestParameters.acceptLanguage !== null) {
            headerParameters['Accept-Language'] = String(requestParameters.acceptLanguage);
        }

        if (requestParameters.ifNoneMatch !== undefined && requestParameters.ifNoneMatch !== null) {
            headerParameters['If-None-Match'] = String(requestParameters.ifNoneMatch);
        }

        const response = await this.request({
            path: `/search/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSearchOkFromJSON(jsonValue));
    }

    /**
     * Search for entities that match a given sub-string.  --- Alternate route: `/dev/search/`  Alternate route: `/legacy/search/`  Alternate route: `/v2/search/`  --- This route is cached for up to 3600 seconds
     * Search on a string
     */
    async getSearch(requestParameters: GetSearchRequest): Promise<GetSearchOk> {
        const response = await this.getSearchRaw(requestParameters);
        return await response.value();
    }

}

/**
    * @export
    * @enum {string}
    */
export enum GetCharactersCharacterIdSearchCategoriesEnum {
    Agent = 'agent',
    Alliance = 'alliance',
    Character = 'character',
    Constellation = 'constellation',
    Corporation = 'corporation',
    Faction = 'faction',
    InventoryType = 'inventory_type',
    Region = 'region',
    SolarSystem = 'solar_system',
    Station = 'station',
    Structure = 'structure'
}
/**
    * @export
    * @enum {string}
    */
export enum GetCharactersCharacterIdSearchAcceptLanguageEnum {
    EnUs = 'en-us',
    Zh = 'zh'
}
/**
    * @export
    * @enum {string}
    */
export enum GetCharactersCharacterIdSearchDatasourceEnum {
    Serenity = 'serenity'
}
/**
    * @export
    * @enum {string}
    */
export enum GetCharactersCharacterIdSearchLanguageEnum {
    EnUs = 'en-us',
    Zh = 'zh'
}
/**
    * @export
    * @enum {string}
    */
export enum GetSearchCategoriesEnum {
    Agent = 'agent',
    Alliance = 'alliance',
    Character = 'character',
    Constellation = 'constellation',
    Corporation = 'corporation',
    Faction = 'faction',
    InventoryType = 'inventory_type',
    Region = 'region',
    SolarSystem = 'solar_system',
    Station = 'station'
}
/**
    * @export
    * @enum {string}
    */
export enum GetSearchAcceptLanguageEnum {
    EnUs = 'en-us',
    Zh = 'zh'
}
/**
    * @export
    * @enum {string}
    */
export enum GetSearchDatasourceEnum {
    Serenity = 'serenity'
}
/**
    * @export
    * @enum {string}
    */
export enum GetSearchLanguageEnum {
    EnUs = 'en-us',
    Zh = 'zh'
}
